name: Award

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@v1
      - uses: astral-sh/setup-uv@v5

      - uses: actions/checkout@v4
        with:
          repository: xingalfred/award
          token: ${{ secrets.GH_PAT }}
          path: app

      - uses: actions/setup-python@v5
        with:
          python-version-file: app/.python-version

      - uses: actions/checkout@v4
        with:
          repository: xingalfred/award-db
          token: ${{ secrets.GH_PAT }}
          path: data

      - name: Run
        run: uv run --no-dev awardx route
        working-directory: app
        env:
          _TYPER_STANDARD_TRACEBACK: 1
          LOGGING_CONFIG_PATH: logging.yaml
          SQLITE_DB_PATH: ${{ github.workspace }}/data/award.db

      # - name: Run
      #   run: uv run --no-dev awardx itinerary SYD AMS
      #   working-directory: app
      #   env:
      #     _TYPER_STANDARD_TRACEBACK: 1
      #     LOGGING_CONFIG_PATH: logging.yaml
      #     SQLITE_DB_PATH: ${{ github.workspace }}/data/award.db

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repoistory: data
